import moment from "moment";

export const STATUSES = {
  APPROVED: "APPROVED",
  COMPLETED: "COMPLETED",
  DECLINED: "DECLINED",
  NEW: "NEW",
  PENDING: "PENDING",
};
export const Transactions = [
  {
    amount: 10,
    currency: "USD",
    date: moment().subtract(1, "day").toDate(),
    desctiption: "На пилюльки",
    id: "1",
    reciever: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    sender: "OsKPjWjBsManRoEYb164r0gyWAG3",
    status: STATUSES.NEW,
    updated: moment().subtract(1, "day").toDate(),
  },
  {
    amount: 11,
    currency: "USD",
    date: moment().subtract(2, "day").toDate(),
    desctiption: "На пилюльки",
    id: "2",
    reciever: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    sender: "OsKPjWjBsManRoEYb164r0gyWAG3",
    status: STATUSES.PENDING,
    updated: moment().subtract(2, "day").toDate(),
  },
  {
    amount: 12,
    currency: "BHT",
    date: moment().subtract(3, "day").toDate(),
    desctiption: "Хотел наебать сука",
    id: "3",
    reciever: "OsKPjWjBsManRoEYb164r0gyWAG3",
    sender: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    status: STATUSES.DECLINED,
    updated: moment().subtract(3, "day").toDate(),
  },
  {
    amount: 13,
    currency: "USD",
    date: moment().subtract(4, "day").toDate(),
    desctiption: "Правильно говоришь",
    id: "4",
    reciever: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    sender: "OsKPjWjBsManRoEYb164r0gyWAG3",
    status: STATUSES.APPROVED,
    updated: moment().subtract(4, "day").toDate(),
  },
  {
    amount: 14,
    currency: "BHT",
    date: moment().subtract(5, "day").toDate(),
    desctiption: "Закрыли вопросик",
    id: "5",
    reciever: "lta8hLCcdlPJNk9WbuHzMwV8n6r1",
    sender: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    status: STATUSES.COMPLETED,
    updated: moment().subtract(5, "day").toDate(),
  },
  {
    amount: 120,
    currency: "USD",
    date: moment().subtract(1, "day").toDate(),
    desctiption: "За отбеливание ануса",
    id: "6",
    reciever: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    sender: "OsKPjWjBsManRoEYb164r0gyWAG3",
    status: STATUSES.NEW,
    updated: moment().subtract(1, "day").toDate(),
  },
  {
    amount: 300,
    currency: "BHT",
    date: moment().subtract(2, "day").toDate(),
    desctiption: "За пивко",
    id: "7",
    reciever: "bA985VJfVtcLkCnSILwUlPEuIAR2",
    sender: "OsKPjWjBsManRoEYb164r0gyWAG3",
    status: STATUSES.PENDING,
    updated: moment().subtract(2, "day").toDate(),
  },
  {
    amount: 5000,
    currency: "BHT",
    date: moment().subtract(7, "day").toDate(),
    desctiption: "набор шлюх",
    id: "8",
    reciever: "bA985VJfVtcLkCnSILwUlPEuIAR2",
    sender: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    status: STATUSES.DECLINED,
    updated: moment().subtract(7, "day").toDate(),
  },
  {
    amount: 13,
    currency: "USD",
    date: moment().subtract(5, "day").toDate(),
    desctiption: "крэм от загара",
    id: "9",
    reciever: "YmtqyOfUl2ahTVKY7AJdPz7ljL02",
    sender: "Ixjo8LoWOaTFYgvCABTpYC9OTax1",
    status: STATUSES.APPROVED,
    updated: moment().subtract(5, "day").toDate(),
  },
  {
    amount: 50,
    currency: "BHT",
    date: moment().subtract(10, "day").toDate(),
    desctiption: "Хлоргекседин",
    id: "10",
    reciever: "bA985VJfVtcLkCnSILwUlPEuIAR2",
    sender: "Ixjo8LoWOaTFYgvCABTpYC9OTax1",
    status: STATUSES.COMPLETED,
    updated: moment().subtract(10, "day").toDate(),
  },
];
